input_type: "mesh"
output_type: "occ" # or sdf or occ
in_out: True
augment_on_the_fly: False
mesh_jitter: False
dataset_folder: "./data/02691156"
wandb_dir: .
batch_size: 2048
lr: 1e-2
model_type: mlp_3d
bayesian: False
logging_root: './logs'
shape_modify: 'no'
exp_name: "insert_name_here"
steps_til_summary: 100
epochs_til_ckpt: 1
hidden_features: 128
kl_weight: 0
epochs: 5000
scheduler:
  type: adaptive
  step_size: 30
  gamma: 0.1
  min_lr: 1e-5
  patience: 50
  patience_adaptive: 10
  factor: 0.8
  threshold: 0
multi_process:
  enabled: False
  part_id: 0
  n_of_parts: 4
  first_weights_name:
  ignore_first: False
n_points: 100000
is_meta: True
strategy: first_weights
clip_grad: False
out_act: sigmoid
mlp_config:
  out_size: 1
  use_leaky_relu: False
  hidden_neurons: [128, 128, 128]
  multires: 4
  move: False